---
title: These Texts
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
    permalink: "/posts/:year/:month/:day/:hour:minute:year/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:year/:month/:day/:hour:minute:year/"
    chats:
    - message:
- scope:
    path: ''
    type: pages
  values:
    layout: page
about_text: "These Texts is a collection of messages I've received from people I know,
  or knew at some point. The messages are organized chronically—each one roughly representing
  1 week from the last three years. \n\nThe project is roughly inspired by [Jamie
  Livingston](http://photooftheday.hughcrawford.com/), [Miranda July](http://wethinkalone.com/),
  and the slew of similar works [already](http://www.textsfromlastnight.com/) out
  there."
error_text: 404. Sorry, but his page doesn’t exist. Go back.
plugins:
- jekyll-paginate
paginate: 15
paginate_path: page:num
