---
title: These Texts
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:year/:month/:day/:hour:minute:year/"
    chats:
    - message: 
- scope:
    path: ''
    type: pages
  values:
    layout: page
about_text: "These Texts is a record of text messages I've received between June 2014
  through June 2020. The messages are organized chronologically. \n\nBuilt by [Will
  Anderson](http://willanderson.co/). "
error_text: 404. Sorry, but his page doesn’t exist. Go back.
plugins:
- jekyll-paginate
paginate: 30
paginate_path: page:num
